apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: national-parks-app
    component: parksmap
    role: frontend
  name: parksmap
  namespace: national-parks
spec:
  selector:
    matchLabels:
      app: parksmap
  replicas: 1
  template:
    metadata:
      labels:
        app: parksmap
        deploymentconfig: parksmap
    spec:
      containers:
        - name: parksmap
          image: >-
            quay.io/mmondics/national-parks-web-manifest:v1
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: parksmap
  name: parksmap
  namespace: national-parks
spec:
  selector:
    app: parksmap
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: parksmap
  name: parksmap
  namespace: national-parks
spec:
  path: /
  to:
    kind: Service
    name: parksmap
    weight: 100
  port:
    targetPort: 8080-tcp
